# 网站标题
title: DocX在做什么
# 网站标题后缀
suffix: Audio-Blog
# 作者名称
author: DocX
# 网站关键字
keyword: Wwise,Game Audio,Unity,游戏音频,技术音频
#false是否开启文章背景图显示(随机图片)
is_article_img: true  
# 网站描述
web_description: 此网站为DocX个人博客与音频作品集记录
# 首页文章布局 默认 'card' 可选择 'block-card'
home_layout: block-card
# 导航名称
menus_title:
  home: HOME
  showreel: SHOWREEL
  archive: ARCHIVE
  categories: CATEGORIES
  links: LINKS
  about: ABOUT
# 导航 （不建议修改）
menus:
  home: /
  showreel: /showreel
  archive: /archives
  categories: /categories
  links: /links
  about: /about
  
# logo
logo: /image/logo.png
# 网页标签上那个小图标 一定要用本地存储
icon: /image/favicon.ico
# 每个页面的展示的图标和一句话
headers:
    home: {
      message: "WELCOME TO MY BLOG! :)",
      icon: "/image/logo.png"
    }
    archives: {
      # 这里会替换掉两个变量{ year 年，number 总数 } 当然也可以不写这两个变量
      message: "居然用了 year 年一共才写了 number 篇文章!",
      icon: "https://cdn.jsdelivr.net/gh/duogongneng/MyBlogImg/imgicon-remixicon.svg"
    }
    tags: {
      message: "来看看都有啥",
      icon: "https://cdn.jsdelivr.net/gh/duogongneng/MyBlogImg/imgtags.svg"
    }
    links: {
      message: "神秘小网站",
      icon: "https://cdn.jsdelivr.net/gh/duogongneng/MyBlogImg/imga20r7-cftji.svg"
    }
    categories: {
      message: "分类 & 标签",
      icon: "https://cdn.jsdelivr.net/gh/duogongneng/MyBlogImg/imgblogmyCategory.svg"
    }
    showreel: {
      message: "音效设计作品集 · Sound Design Showreel",
      icon: "/image/logo.png"
    }

# 网页访问统计
web_analytics:  
  enable: false #需要改为true
  baidu: 4b5fe1472f22fadsfs  # （替换）百度统计的 Key，参见 https://tongji.baidu.com/sc-web/10000033910/home/site/getjs?siteId=13751376 代码获取中 hm.js? 后边的字符串
# 评论（Giscus - 基于 GitHub Discussions）
giscus:
  enable: true
  repo: DooocX/DooocX.github.io
  repo_id: R_kgDONuR9yQ
  category: Announcements
  category_id: DIC_kwDONuR9yc4C7fTb
  mapping: pathname
  strict: 0
  reactions_enabled: 1
  emit_metadata: 0
  input_position: top
  theme: light
  lang: zh-CN

# 底部显示的图标（github 或者其他）
bottomIcon: 
  #可以多个
  - {
    name: 'Github',
    iconLink: '/image/icon-github.svg',
    toUrl: 'https://github.com/DooocX'
  }
  - {
    name: 'Bilibili',
    iconLink: '/image/icon-bilibili.svg',
    toUrl: 'https://space.bilibili.com/5292339'
  }
  - {
    name: 'Email',
    iconLink: '/image/icon-email.svg',
    toUrl: 'mailto:your-email@example.com'
  }
# 友情链接
linksList:
  - {
    title: 'Hexo-Quiet-Theme',
    intro: '源码与配置教程',
    link: 'https://github.com/79E/hexo-theme-quiet',
    image: 'https://cdn.jsdelivr.net/gh/duogongneng/MyBlogImg/imgIMG_7327.jpeg'
  }

#默认的cover (默认缩略图) 在没有填写（这里可以替换（可以是api也可以是固定的图））
# https://api.ixiaowai.cn/gqapi/gqapi.php
# https://tuapi.eees.cc/api.php?type=302&category=fengjing
default_cover: https://api.ixiaowai.cn/gqapi/gqapi.php
